#!/bin/bash

NAME="myproj"
DIR=/home/apptest/myproj
USER=apptest
GROUP=apptest
WORKERS=3
BIND=unix:/home/apptest/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=project.settings_prod
DJANGO_WSGI_MODULE=project.wsgi
LOG_LEVEL=error

cd $DIR
source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-